language: julia
os:
    - linux
    - osx
julia:
    - 0.5
    - nightly
notifications:
    email: false
sudo: false
addons:
    apt_packages:
        - gfortran
script:
    - cd src
    - julia -e 'Pkg.add("ForwardDiff")'
    - make linux64
after_success:
    - echo $TRAVIS_JULIA_VERSION
